---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  vars:
    postgres_rhel7_repo:  pgdg-redhat-repo-42.0-11.noarch
    postgres_packages:
      - postgresql10 
      - postgresql10-server 
      - postgresql10-contrib 
      - postgresql10-libs
    postgres_library: "python-psycopg2"
    postgres_10_data_dir: /var/lib/pgsql/10/data

  tasks:

    - name: Remove Postgres packages
      package:
        name: "{{ __package }}"
        state: absent
      loop: 
        - "{{ postgres_rhel7_repo }}"        
        - "{{ postgres_library }}"
        - "{{ postgres_packages }}"
      loop_control:
        loop_var: __package

    - name: Remove Postgres 10 data directory
      file:
        path: /var/lib/pgsql/10
        state: absent

    - name: Remove Postgres user
      user:
        name: postgres
        state: absent
...        
