---
- name:           Remove most packages and configuration to re-run lab
  hosts:          all
  become:         yes
  gather_facts:   true
  vars:
    removal_packages:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs

    removal_paths:  
      - /var/lib/pgsql

  tasks:

    - name: Remove yum packages from hosts
      yum:
        name:     "{{ package }}"
        state:    absent
      loop: "{{ removal_packages }}"
      loop_control:
        loop_var: package
      tags:
        - remove_yum_packages

    - name: Remove files and directories
      file:
        name:     "{{ path }}"
        state:    absent
      loop: "{{ removal_paths }}"
      loop_control:
        loop_var: path
      tags:
        - remove_paths
...
